import Sidebar from "./Sidebar"
import NowPlaying from "./components/NowPlaying"
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <div className="flex relative min-h-screen"> {/* Added a flex container and relative positioning */}
      <div> {/* Removed h-screen */}
        <Sidebar/>
      </div>
      <div className="flex-1"> {/* Container for children */}
        {children}
      </div>
      <div className="absolute top-4 right-10"> {/* Container for now playing components with absolute positioning */}
        <NowPlaying/ > 
        
      </div>
    </div>
  )
}
